version: '3.9'

volumes:
    docker-data: {}

networks:
    app-network:
        driver: bridge

services:
    # redis http://localhost:8081
    redis:
        image: redis:alpine
        container_name: db-redis
        command: ["redis-server", "--appendonly", "yes"]
        restart: always
        volumes:
            - ./docker-data/redis/data:/data
        ports:
            - ${REDIS_PORT:-6379}:6379
        networks:
            - app-network

    mongo:
        image: mongo
        container_name: db-mongo
        restart: always
        command: mongod
        environment:
#            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
#            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
            - MONGO_INITDB_DATABASE=${MONGO_DB:-titan}
        volumes:
            - './docker-data/mongodb:/data/db'
        ports:
            - ${MONGO_PORT:-27019}:27017
        networks:
            - app-network